sudo: required
language: python

notifications:
  email: false

python:
  - "3.6"

before_script:
  - wget https://releases.hashicorp.com/terraform/0.9.11/terraform_0.9.11_linux_amd64.zip -O /tmp/terraform.zip
  - unzip /tmp/terraform.zip -d terraform/
  - export PATH=$PATH:$PWD/terraform/

install:
  - make deps

script:
  - make lint
  - make test
